import { Injectable, NotFoundException } from '@nestjs/common';
import { db } from '../../database/client';
import { codeGuidelines, aiAudits } from '../../database/schema';
import { eq, sql, desc } from 'drizzle-orm';

@Injectable()
export class StandardsService {
  async create(input: {
    organizationId: string;
    name: string;
    pattern: string;
    description?: string;
    severity?: string;
    category?: string;
  }) {
    const [guideline] = await db
      .insert(codeGuidelines)
      .values({
        organizationId: input.organizationId,
        name: input.name,
        description: input.description ?? null,
        pattern: input.pattern,
        severity: (input.severity as 'error' | 'warning' | 'info') || 'warning',
        category: input.category || 'general',
      })
      .returning();

    return guideline;
  }

  async getById(id: string) {
    const [guideline] = await db
      .select()
      .from(codeGuidelines)
      .where(eq(codeGuidelines.id, id))
      .limit(1);

    if (!guideline) throw new NotFoundException(`Guideline ${id} not found`);
    return guideline;
  }

  async listByOrg(organizationId: string) {
    return db
      .select()
      .from(codeGuidelines)
      .where(eq(codeGuidelines.organizationId, organizationId));
  }

  async update(id: string, data: Record<string, unknown>) {
    await this.getById(id);

    const [updated] = await db
      .update(codeGuidelines)
      .set({ ...data, updatedAt: new Date() })
      .where(eq(codeGuidelines.id, id))
      .returning();

    return updated;
  }

  async remove(id: string) {
    await this.getById(id);
    await db.delete(codeGuidelines).where(eq(codeGuidelines.id, id));
    return { deleted: true };
  }

  /**
   * Generate a paste-able Markdown context string for AI coding tools.
   * Matches the specification's `/api/v1/standards/context/{org_id}` endpoint.
   */
  async getContextMarkdown(organizationId: string) {
    const guidelines = await this.listByOrg(organizationId);
    const topViolations = await this.getTopViolations(organizationId, 30);

    const guidelineList = guidelines
      .filter((g) => g.isEnabled)
      .map((g) => `- **${g.name}** [${g.severity}]: ${g.description || 'No description'}\n  Pattern: \`${g.pattern}\``)
      .join('\n');

    const violationList = topViolations
      .map((v) => `- ${v.guidelineName}: ${v.count} violations`)
      .join('\n');

    const contextMarkdown = `# Organizational Coding Standards (Auto-generated by AI Code Governance)

## Active Rules (${guidelines.filter((g) => g.isEnabled).length} total)
${guidelineList}

## Common AI Mistakes in This Codebase (Last 30 Days)
${violationList || 'No violations recorded yet.'}

## Task Scope Boundaries
Always check the decomposed task boundaries before coding.
Maximum 3 files, 150 lines per task. Do not touch explicitly forbidden files.
`;

    return {
      contextMarkdown,
      organizationId,
      generatedAt: new Date().toISOString(),
    };
  }

  /**
   * Get top violation patterns from audit history.
   */
  async getTopViolations(organizationId: string, days: number) {
    const since = new Date();
    since.setDate(since.getDate() - days);

    // Aggregate violation counts from recent audits
    // (In production this would join with violation_detail table)
    const audits = await db
      .select({
        verdict: aiAudits.verdict,
        count: sql<number>`count(*)::int`,
      })
      .from(aiAudits)
      .where(eq(aiAudits.organizationId, organizationId))
      .groupBy(aiAudits.verdict)
      .orderBy(desc(sql`count(*)`));

    const total = audits.reduce((sum, a) => sum + a.count, 0);
    const failCount = audits.find((a) => a.verdict === 'fail')?.count ?? 0;
    const passRate = total > 0 ? ((total - failCount) / total * 100).toFixed(1) : '100.0';

    return {
      totalAudits: total,
      failCount,
      passRate: `${passRate}%`,
      breakdown: audits,
      period: `last ${days} days`,
    };
  }
}
